### ISSUE TITLE
Spain clean up/finish

### ISSUE THREAD

**Issue by Johansens** [Johansens/JFU_testing#1]
- anachisten entfernen 
- mission/decision die anzeigt wann der civil war startet
- gold reserves auf 01.09.1937 hard scripten
- sonstige Reste von demo spain entfernen (focus tree, decisions, events etc)
- praktikable möglichkeit ports/airports nach civil war komplet zu entfernen? (atm bekomm ich airports nur auf 1 runter gesetzt)
- eventuelle balance changes -> Ziel wäre Spain mehr early output zu geben dafür weniger late game output| 2-4 tanks für africa?/max. 12-16 tanks für Barb?)
-

**Comment by TimConti** [comment]
@Johansens 
"gold reserves auf 01.09.1937 hard scripten" mit user interaction oder reicht es eine timed idea zu adden?
"praktikable möglichkeit ports/airports nach civil war komplet zu entfernen?" Warum sollten ports und airfields nach civil war entfernt werden?

**Comment by Johansens** [comment]
timed idea reicht für gold reserven, wegen airport/port - spain ist ja "voluteer nation" und deswegen soll die achse die ports/airport vom dem nicht verwenden können. andere mods die spain so haben z.b horst/lw haben die ports airports von anfang an entfernt oder oak desen lösung aber mMn absoluter schwachsinn ist: setzten airports auf eins und geben denen täglich 100% dmg...
